name: Update sponsors

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - run: yarn

      - name: Update sponsors
        run: yarn build
        env:
          SPONSORKIT_PATREON_TOKEN: ${{ secrets.SPONSORS_TOKEN }}

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update sponsors'
          add: 'sponsors.*'
