name: Update sponsors

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: yarn

      - name: Update sponsors
        run: npm run build
        env:
          SPONSORKIT_PATREON_TOKEN: ${{ secrets.SPONSORS_TOKEN }}

      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          message: 'Update sponsors'
          add: 'sponsors.*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
